receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: true
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: true

exporters:
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
    # tenant_id: "tenant1"
    # format: json
    # label_allowed_pattern: "^[a-zA-Z0-9_]+$"
    # record_attributes:
    #   - level
    #   - event.name
    # record_resources:
    #   - service.name
    #   - service.instance.id
    # static_labels:
    #   job: "otel-collector"
    #   instance: "collector-1"


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
