receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    loglevel: debug
  # debug: {}
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      exporters: [otlp/tempo]
