-- Create "profiles" table
CREATE TABLE "profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "user_id" bigint NOT NULL, "key" bigint NOT NULL, "value" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"));
-- Create index "profile_user_id" to table: "profiles"
CREATE INDEX "profile_user_id" ON "profiles" ("user_id");
-- Create index "profile_user_id_key" to table: "profiles"
CREATE INDEX "profile_user_id_key" ON "profiles" ("user_id", "key");
-- Create index "profile_user_id_key_is_active" to table: "profiles"
CREATE INDEX "profile_user_id_key_is_active" ON "profiles" ("user_id", "key", "is_active");
-- Set comment to table: "profiles"
COMMENT ON TABLE "profiles" IS 'User profile, in the format of key-value pair';
