// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "key", Type: field.TypeInt},
		{Name: "value", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Comment:    "User profile, in the format of key-value pair",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "profile_user_id",
				Unique:  false,
				Columns: []*schema.Column{ProfilesColumns[3]},
			},
			{
				Name:    "profile_user_id_key",
				Unique:  false,
				Columns: []*schema.Column{ProfilesColumns[3], ProfilesColumns[4]},
			},
			{
				Name:    "profile_user_id_key_is_active",
				Unique:  false,
				Columns: []*schema.Column{ProfilesColumns[3], ProfilesColumns[4], ProfilesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProfilesTable,
	}
)

func init() {
	ProfilesTable.Annotation = &entsql.Annotation{}
}
